# Generated by Django 4.0.4 on 2022-05-20 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_thread'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='thread',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='message.thread'),
        ),
    ]
