# Generated by Django 4.0.4 on 2022-05-07 19:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='user_liked',
            field=models.ManyToManyField(blank=True, default='', related_name='users_liked_post', to=settings.AUTH_USER_MODEL),
        ),
    ]
