# Generated by Django 4.0.4 on 2022-05-07 19:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_alter_post_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user_liked',
            field=models.ManyToManyField(blank=True, default='', related_name='users_liked_comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
