# Generated by Django 4.0.4 on 2022-05-08 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_comment_replys'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='user_liked',
        ),
    ]
