# Generated by Django 4.0.4 on 2022-05-08 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_reply_user_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replys',
            field=models.ManyToManyField(blank=True, default='', related_name='comment_replys', to='post.reply'),
        ),
    ]
