# Generated by Django 4.0.4 on 2022-05-10 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_comment_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-likes']},
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
