# Generated by Django 4.0.4 on 2022-05-10 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_options_post_views_alter_post_date_posted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-likes', '-views', '-comments_number', '-date_posted']},
        ),
    ]
