# Generated by Django 4.0.4 on 2022-05-13 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_post_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-date_posted']},
        ),
    ]
