# Generated by Django 4.0.4 on 2022-05-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_remove_post_comments_number_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.FileField(default='', upload_to='files'),
        ),
    ]
