# Generated by Django 4.0.4 on 2022-05-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_users',
            field=models.ManyToManyField(blank=True, to='users.profile'),
        ),
    ]
