# Generated by Django 4.0.4 on 2022-05-17 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_options_profile_followers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['-followers']},
        ),
        migrations.AddField(
            model_name='profile',
            name='theme',
            field=models.CharField(default='light', max_length=10),
        ),
    ]
